# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Free Compiler Camp Classroom"
email:
description: > # this means to ignore newlines until "baseurl:"
  Play with Compilers tutorials

baseurl: # the subpath of your site, e.g. /blog
url: "http://freecompilercamp.org" # the base hostname & protocol for your site

#sidebar
default-image: docker-logo.svg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: LLNL
copyright:
   name: Docker, Inc.
   link: 'https://docker.com'

# Build settings
highlighter: rouge
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-89019737-1


#social
#facebook: https://www.facebook.com/docker.run
#twitter: https://twitter.com/docker
github: https://github.com/freeCompilerCamp/play-with-compiler
#twitter_username: docker
#youtube: https://youtube.com/docker.run

#facebook like box
#fb-app-id: 549480635219583
#fb-page-url: https://www.facebook.com/docker.run/
#fb-page-title: Docker

# Sass style
sass:
  style: compressed

# Gems
gems: [jekyll-paginate]

# Plugins
plugins_dir:
  - jekyll-paginate

# Play with Docker
pwdurl: http://racedetection.org

# Upload endpoint for closed-book exams
exam_endpoint: http://ec2-54-241-120-89.us-west-1.compute.amazonaws.com/llnl-freecompilercamp/freecc_exams/

# Default docker image
default_docker_image: freecompilercamp/pwc:full
